language: cpp

compiler: gcc

os: linux

sudo: required

dist: bionic

before_install:
	- sudo apt-get update -qq
 	- sudo apt-get install -qq qt5-dev-tools

script:
  - cd ./TestLib/
  - mkdir build && cd build
  - cmake .. && make
  
# after success:
#  - bash <(curl -s https://codecov.io/bash) 

branches:
    only:
    - dev
    - /^feature/*$\
    - /^refactor/*$\
    - /^fix/*$\

notifications:
    email: false

