language: cpp

compiler: gcc

os: linux

dist: focal

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

addons:
  apt:
    packages:
     - gcc-10
     - cmake
     - qtbase5-dev
     - qtbase5-dev-tools
     - qt5-default
     - libcuda-10.2
     - libopencv-dev
     - libarrayfire-unified-dev
     - libboost-all-dev
    
script:
  - cd ./TestLib/
  - mkdir build && cd build
  - cmake .. && make
  - ./unittests
  
after success:
  - bash <(curl -s https://codecov.io/bash) 

branches:
    only:
    - dev
    - /^feature/*$\
    - /^refactor/*$\
    - /^fix/*$\

notifications:
    email: false

