language: cpp

compiler: gcc

os: linux

dist: bionic

before_install:
 	- sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 	- sudo apt-get install qt5-default qttools5-dev-tools

script:
  - cd ./TestLib/
  - mkdir build && cd build
  - cmake .. && make
  
# after success:
#  - bash <(curl -s https://codecov.io/bash) 

branches:
    only:
    - dev
    - /^feature/*$\
    - /^refactor/*$\
#    - /^fix/*$\

notifications:
    email: false

