language: cpp

compiler: gcc

os: linux

sudo: required

dist: bionic

script:
  - cd ./test/
  - qmake -makefile -Wall
  - make
  
after success:
  - bash <(curl -s https://codecov.io/bash) 

branches:
    only:
    - dev
    - /^feature/*$\
    - /^refactor/*$\
    - /^fix/*$\

notifications:
    email: false

